In [64]:
import numpy as np
import pandas as pd

In [65]:
#1
a=pd.read_csv('C:\\Users\\y20cs74\\Downloads\\winequality-red.csv')
a

fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
1      7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5                                                                                                                     
2     7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...                                                                                                                     
3     11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...                                                                                                                     
4      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
...                                                 ...                                                                                                                     
1594  6.2;0.6;0.08;2;0.09;32;44;0.9949;3.45;0.58;10.5;5                                                                                                                     
1595  5.9;0.55;0.1;2.2;0.062;39;51;0.99512;3.52;0.76...                                                                                                                     
1596  6.3;0.51;0.13;2.3;0.076;29;40;0.99574;3.42;0.7...                                                                                                                     
1597  5.9;0.645;0.12;2;0.075;32;44;0.99547;3.57;0.71...                                                                                                                     
1598  6;0.31;0.47;3.6;0.067;18;42;0.99549;3.39;0.66;...                                                                                                                     

[1599 rows x 1 columns]

In [66]:
#2
l=a.values.tolist()
for i in range(len(l)):
    l[i]=l[i][0].split(";")
wines=np.array(l)
wines.dtype

dtype('<U16')

In [67]:
wines=wines.astype(np.float64)
wines.dtype

dtype('float64')

In [68]:
#3
wines.shape

(1599, 12)

In [69]:
#4
wines[2][3]

2.3

In [70]:
#5
wines[:3,3]

array([1.9, 2.6, 2.3])

In [71]:
#6
wines[:,2]

array([0.  , 0.  , 0.04, ..., 0.13, 0.12, 0.47])

In [72]:
#7
wines[4]

array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ,  5.    ])

In [73]:
#8
wines[1][5]=10

In [74]:
#9
slice_new=wines[:,9]
slice_new

array([0.56, 0.68, 0.65, ..., 0.75, 0.71, 0.66])

In [75]:
slice_new[:]=666
slice_new

array([666., 666., 666., ..., 666., 666., 666.])

In [76]:
#10
wines

array([[7.40e+00, 7.00e-01, 0.00e+00, ..., 6.66e+02, 9.40e+00, 5.00e+00],
       [7.80e+00, 8.80e-01, 0.00e+00, ..., 6.66e+02, 9.80e+00, 5.00e+00],
       [7.80e+00, 7.60e-01, 4.00e-02, ..., 6.66e+02, 9.80e+00, 5.00e+00],
       ...,
       [6.30e+00, 5.10e-01, 1.30e-01, ..., 6.66e+02, 1.10e+01, 6.00e+00],
       [5.90e+00, 6.45e-01, 1.20e-01, ..., 6.66e+02, 1.02e+01, 5.00e+00],
       [6.00e+00, 3.10e-01, 4.70e-01, ..., 6.66e+02, 1.10e+01, 6.00e+00]])

In [56]:
#11
print(wines.dtype)
wines=wines.astype(int)
print(wines.dtype)

float64
int32


In [77]:
#12
wines[:,-1]*10

array([50., 50., 50., ..., 60., 50., 60.])

In [78]:
#13
np.sum(wines)

1215951.40194

In [79]:
#14
np.sum(wines,axis=1)

array([739.9838 , 773.3748 , 765.049  , ..., 765.73174, 770.50547,
       757.83249])

In [80]:
#15
np.sum(wines,axis=0)

array([1.33031000e+04, 8.43985000e+02, 4.33290000e+02, 4.05955000e+03,
       1.39859000e+02, 2.53690000e+04, 7.43020000e+04, 1.59379794e+03,
       5.29447000e+03, 1.06493400e+06, 1.66663500e+04, 9.01200000e+03])

In [81]:
#16
wines[:,-1]+wines[:,-1]

array([10., 10., 10., ..., 12., 10., 12.])

In [82]:
#17
wines[:,-1]*wines[:,-2]

array([47., 49., 49., ..., 66., 51., 66.])

In [88]:
#18
wines[wines[:,-1]>5][:,-1]

array([6., 7., 7., 7., 6., 6., 6., 6., 6., 6., 6., 6., 7., 6., 6., 6., 6.,
       6., 7., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 7., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 7., 7., 6., 7., 7., 7., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 7., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 7., 7., 6.,
       6., 6., 6., 6., 6., 7., 7., 8., 6., 6., 6., 6., 6., 6., 6., 8., 7.,
       6., 7., 7., 6., 6., 7., 7., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 7., 6., 7., 6., 6., 6., 7., 6., 6., 6., 6., 7., 7.,
       6., 6., 7., 6., 6., 6., 6., 6., 7., 6., 6., 6., 6., 6., 6., 6., 7.,
       7., 6., 6., 7., 6., 7., 7., 6., 6., 6., 7., 6., 7., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 7., 8., 6., 7., 6., 6., 6., 6., 6., 6., 6.,
       7., 6., 6., 7., 6., 6., 7., 7., 7., 7., 6., 6., 6., 7., 6., 6., 6.,
       6., 6., 8., 6., 7., 7., 7., 6., 6., 6., 6., 6., 6., 7., 8., 7., 6.,
       6., 6., 6., 6., 6.

In [87]:
#19
print(wines[:,-1]==10)

[False False False ... False False False]


In [89]:
#20
wines[wines[:,-1]>7]

array([[7.9000e+00, 3.5000e-01, 4.6000e-01, 3.6000e+00, 7.8000e-02,
        1.5000e+01, 3.7000e+01, 9.9730e-01, 3.3500e+00, 6.6600e+02,
        1.2800e+01, 8.0000e+00],
       [1.0300e+01, 3.2000e-01, 4.5000e-01, 6.4000e+00, 7.3000e-02,
        5.0000e+00, 1.3000e+01, 9.9760e-01, 3.2300e+00, 6.6600e+02,
        1.2600e+01, 8.0000e+00],
       [5.6000e+00, 8.5000e-01, 5.0000e-02, 1.4000e+00, 4.5000e-02,
        1.2000e+01, 8.8000e+01, 9.9240e-01, 3.5600e+00, 6.6600e+02,
        1.2900e+01, 8.0000e+00],
       [1.2600e+01, 3.1000e-01, 7.2000e-01, 2.2000e+00, 7.2000e-02,
        6.0000e+00, 2.9000e+01, 9.9870e-01, 2.8800e+00, 6.6600e+02,
        9.8000e+00, 8.0000e+00],
       [1.1300e+01, 6.2000e-01, 6.7000e-01, 5.2000e+00, 8.6000e-02,
        6.0000e+00, 1.9000e+01, 9.9880e-01, 3.2200e+00, 6.6600e+02,
        1.3400e+01, 8.0000e+00],
       [9.4000e+00, 3.0000e-01, 5.6000e-01, 2.8000e+00, 8.0000e-02,
        6.0000e+00, 1.7000e+01, 9.9640e-01, 3.1500e+00, 6.6600e+02,
        1.1700e+01,

In [92]:
wines[(wines[:,-2]>10) & (wines[:,-1]>7)]

array([[7.9000e+00, 3.5000e-01, 4.6000e-01, 3.6000e+00, 7.8000e-02,
        1.5000e+01, 3.7000e+01, 9.9730e-01, 3.3500e+00, 6.6600e+02,
        1.2800e+01, 8.0000e+00],
       [1.0300e+01, 3.2000e-01, 4.5000e-01, 6.4000e+00, 7.3000e-02,
        5.0000e+00, 1.3000e+01, 9.9760e-01, 3.2300e+00, 6.6600e+02,
        1.2600e+01, 8.0000e+00],
       [5.6000e+00, 8.5000e-01, 5.0000e-02, 1.4000e+00, 4.5000e-02,
        1.2000e+01, 8.8000e+01, 9.9240e-01, 3.5600e+00, 6.6600e+02,
        1.2900e+01, 8.0000e+00],
       [1.1300e+01, 6.2000e-01, 6.7000e-01, 5.2000e+00, 8.6000e-02,
        6.0000e+00, 1.9000e+01, 9.9880e-01, 3.2200e+00, 6.6600e+02,
        1.3400e+01, 8.0000e+00],
       [9.4000e+00, 3.0000e-01, 5.6000e-01, 2.8000e+00, 8.0000e-02,
        6.0000e+00, 1.7000e+01, 9.9640e-01, 3.1500e+00, 6.6600e+02,
        1.1700e+01, 8.0000e+00],
       [1.0700e+01, 3.5000e-01, 5.3000e-01, 2.6000e+00, 7.0000e-02,
        5.0000e+00, 1.6000e+01, 9.9720e-01, 3.1500e+00, 6.6600e+02,
        1.1000e+01,